name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Lint, typecheck and stylecheck
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prettier (check)
        run: npm run prettier:check

      - name: TypeScript - type check
        run: npm run tsc

      - name: ESLint
        run: npm run eslint

      - name: Stylelint
        run: npm run stylelint

    # To enable deploy later, we can add a separate job that runs `npm run deploy:dev`
    # guarded behind `workflow_dispatch` or specific branches/tags and using GITHUB_TOKEN.
